### ISSUE TITLE
bug php v7.2.xx

### ISSUE THREAD

**Issue by ludwigPop** [cnrs-webkit/cnrswebkit#1]
Le kit affiche un problème dans les rubriques actualités, évènements, annuaires, emploi, médiathèque avec les version de php supérieur à 7.2.xx. 

Warning: count(): Parameter must be an array or an object that implements Countable in C:\wamp64\www\tests\kit-cnrs2\wp-content\themes\cnrswebkit\inc\inc-pages-functions.php on line 680

J'ai contourné le problème avec ce code à la ligne 680.
`
if ($this->post_list_params->selectors /*count($this->post_list_params->selectors ) > 0*/) {
            $filters = [];
            foreach ($this->post_list_params->selectors as $k => &$v) {
                $filters[] = '<div>' . $v . '</div>';
            }
`

**Comment by ChristopheSeguinot** [comment]
Fixé à 3 emplacements dans le code. 
Merci.
